POST http://localhost:3000/register
Content-Type: application/json

{
    "username" : "Aadhi",
    "password" : "aadhi444"
}
###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "Aadhivenkatesh",
    "password" : "aadhi4448"
}
###

GET http://localhost:3000/user/2
Authorization: Brearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTY3MTY1MDB9.Z27cTZqrN0JwyRxPxw1dAKnk51scDMkukhZK1VRfIe4
